"""
render_newsletter.py
--------------------
Takes the categorised, summarised DataFrame and renders a clean
Markdown newsletter file.

Structure:
  - Header with week date
  - Short introduction (written by the LLM)
  - One section per category
  - Short closing note
"""

import os
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from openai import AzureOpenAI


SECTION_ORDER = ["Research Highlights", "Industry News", "Cool Use Cases"]

OUTPUT_DIR = Path("output")


def _generate_intro(client: AzureOpenAI, deployment: str, week_label: str, titles: list[str]) -> str:
    """Ask the LLM to write a short 3-sentence intro paragraph for this week."""
    titles_text = "\n".join(f"- {t}" for t in titles[:8])
    prompt = f"""You are writing the opening paragraph of a weekly AI newsletter for Odido's tech team.
Week: {week_label}

This week's top topics include:
{titles_text}

Write a friendly, energetic 2–3 sentence introduction that summarises the theme of this week's AI news.
Do not use bullet points. Keep it under 60 words."""

    response = client.chat.completions.create(
        model=deployment,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.6,
        max_tokens=100,
    )
    return response.choices[0].message.content.strip()


def _generate_closing(client: AzureOpenAI, deployment: str) -> str:
    """Ask the LLM to write a brief, warm closing note."""
    prompt = """Write a 1–2 sentence closing note for a weekly AI newsletter.
It should be warm, encourage the reader to explore the links, and wish them a great week.
Keep it under 40 words."""

    response = client.chat.completions.create(
        model=deployment,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.6,
        max_tokens=60,
    )
    return response.choices[0].message.content.strip()


def render_newsletter(df: pd.DataFrame, output_path: str = "newsletter.md") -> str:
    """
    Builds the markdown newsletter and writes it to `output_path`.
    Returns the full markdown string.
    """
    client = AzureOpenAI(
        api_key=os.environ["AZURE_OPENAI_API_KEY"],
        azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
        api_version=os.environ.get("AZURE_OPENAI_API_VERSION", "2024-02-01"),
    )
    deployment = os.environ["AZURE_OPENAI_DEPLOYMENT"]

    now = datetime.now(timezone.utc)
    week_label = now.strftime("Week of %B %d, %Y")

    print("Generating newsletter intro...")
    intro = _generate_intro(client, deployment, week_label, df["title"].tolist())

    print("Generating newsletter closing...")
    closing = _generate_closing(client, deployment)

    # --- Build Markdown ---
    lines = []
    lines.append(f"# Odido AI Newsletter — {week_label}\n")
    lines.append(f"> *Generated automatically every week from the latest AI/LLM research and news.*\n")
    lines.append(f"---\n")
    lines.append(f"## 👋 This Week in AI\n")
    lines.append(f"{intro}\n")
    lines.append(f"---\n")

    for section in SECTION_ORDER:
        section_df = df[df["section"] == section]
        if section_df.empty:
            continue

        lines.append(f"## {_section_emoji(section)} {section}\n")

        for _, row in section_df.iterrows():
            title = row.get("title", "Untitled")
            url = row.get("webflow_url", "") or row.get("source_url", "")
            summary = row.get("summary", "")
            company = row.get("company", "")
            date_str = pd.Timestamp(row["created_at"]).strftime("%b %d")

            # Title as a link if we have a URL
            title_md = f"[{title}]({url})" if url else title

            lines.append(f"### {title_md}")
            if company:
                lines.append(f"*{company} · {date_str}*\n")
            else:
                lines.append(f"*{date_str}*\n")
            lines.append(f"{summary}\n")

        lines.append("---\n")

    lines.append(f"## 👋 Until Next Week\n")
    lines.append(f"{closing}\n")
    lines.append(f"\n*This newsletter is auto-generated by the Odido AI Newsletter Pipeline.*")

    markdown = "\n".join(lines)

    # Write to file
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(markdown, encoding="utf-8")
    print(f"Newsletter written to: {output_file.resolve()}")

    return markdown


def _section_emoji(section: str) -> str:
    return {
        "Research Highlights": "🔬",
        "Industry News": "📰",
        "Cool Use Cases": "💡",
    }.get(section, "📌")
